name: softscreenalien
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37566
title: Soft Screen Alien
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73603746-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c4c9cf'
    - '#424242'
    - '#9197a3'
    - '#181715'
    - '#fefefe'
  brandStrength: 0
  lightness: 0.25179380597546697
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
